import type { TabProps } from "./types"

export function OverviewTab({ conference }: TabProps) {
  return (
    <div className="w-full">
      <div className="grid grid-cols-1 lg:grid-cols-10 gap-8 items-start">
        <div className="lg:col-span-7 space-y-6">
          {/* About the Conference */}
          <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
              <h2 className="text-lg font-bold text-navy-900 dark:text-white flex items-center gap-2">
                <span className="material-symbols-outlined text-slate-400">description</span>
                About the Conference
              </h2>
            </div>
            <div className="p-6">
              <p className="text-slate-600 dark:text-slate-300 leading-relaxed italic">
                [To be generated by AI]
              </p>
            </div>
          </section>

          {/* Conference Tracks */}
          <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center">
              <h2 className="text-lg font-bold text-navy-900 dark:text-white flex items-center gap-2">
                <span className="material-symbols-outlined text-slate-400">alt_route</span>
                Conference Tracks
              </h2>
              {conference.tracks && conference.tracks.length > 0 && (
                <span className="text-xs font-medium text-slate-500 bg-slate-100 dark:bg-slate-800 px-2.5 py-1 rounded-full">
                  {conference.tracks.length} Active Tracks
                </span>
              )}
            </div>
            <div className="p-6">
              <div className="flex flex-wrap gap-2">
                {conference.tracks && conference.tracks.length > 0 ? (
                  conference.tracks.map((track, idx) => (
                    <span
                      key={idx}
                      className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-800 border border-slate-200"
                    >
                      {track}
                    </span>
                  ))
                ) : (
                  <span className="text-slate-500 text-sm">No tracks specified</span>
                )}
              </div>
            </div>
          </section>
        </div>

        <div className="lg:col-span-3 space-y-6">
          {/* Details */}
          <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800">
              <h2 className="text-lg font-bold text-navy-900 dark:text-white flex items-center gap-2">
                <span className="material-symbols-outlined text-slate-400">info</span>
                Details
              </h2>
            </div>
            <div className="p-6 space-y-5">
              <div>
                <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                  Synonym
                </span>
                <div className="text-sm font-medium text-navy-900 dark:text-white bg-slate-50 dark:bg-slate-800 inline-block px-2 py-1 rounded border border-slate-200 dark:border-slate-700">
                  {conference.acronym} {conference.year}
                </div>
              </div>
              <div>
                <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                  Venue
                </span>
                <div className="text-sm font-medium text-navy-900 dark:text-white flex items-start gap-2">
                  {conference.location || "Online"}
                </div>
              </div>
              {conference.website && (
                <div>
                  <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                    Website
                  </span>
                  <a
                    className="text-sm font-medium text-blue-600 hover:text-blue-700 hover:underline flex items-center gap-1"
                    href={conference.website}
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    {conference.website}
                    <span className="material-symbols-outlined text-[14px]">open_in_new</span>
                  </a>
                </div>
              )}
              {conference.primary_contact && (
                <div>
                  <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-1">
                    Organizer Contact
                  </span>
                  <a
                    className="text-sm font-medium text-slate-700 dark:text-slate-300 hover:text-navy-900 flex items-center gap-1"
                    href={`mailto:${conference.primary_contact}`}
                  >
                    <span className="material-symbols-outlined text-[16px] text-slate-400">
                      mail
                    </span>
                    {conference.primary_contact}
                  </a>
                </div>
              )}
            </div>
            <div className="bg-slate-50 dark:bg-slate-800/50 p-4 border-t border-slate-200 dark:border-slate-800">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500 font-medium">Conference ID</span>
                <span className="text-xs text-slate-400 font-mono">#{conference.id}</span>
              </div>
            </div>
          </section>

          {/* Keywords */}
          <section className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-800">
              <h2 className="text-lg font-bold text-navy-900 dark:text-white flex items-center gap-2">
                <span className="material-symbols-outlined text-slate-400">label</span>
                Keywords
              </h2>
            </div>
            <div className="p-6">
              <div className="flex flex-wrap gap-2">
                {conference.domain && conference.domain.length > 0 ? (
                  conference.domain.map((keyword, idx) => (
                    <span
                      key={idx}
                      className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-800 border border-slate-200"
                    >
                      {keyword}
                    </span>
                  ))
                ) : (
                  <span className="text-slate-500 text-sm">No keywords specified</span>
                )}
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
