import type { ReviewerConference, AssignmentWithPaper, ReviewerStats } from "@/lib/types"

export const MOCK_MY_CONFERENCES: ReviewerConference[] = [
  {
    id: "1",
    name: "Computer Vision & Pattern Rec.",
    acronym: "CVPR 2024",
    year: 2024,
    description: "Computer Vision & Pattern Rec.",
    submission_deadline: "2024-03-01",
    review_deadline: "2024-05-15",
    camera_ready_deadline: "2024-06-01",
    notification_date: "2024-04-15",
    conference_date: "2024-06-20",
    location: "Seattle, USA",
    status: "active",
    tracks: [],
    reviewed_papers: 3,
    total_papers: 5,
    domain: "Computer Vision",
  },
  {
    id: "2",
    name: "Neural Info. Processing Systems",
    acronym: "NeurIPS 2024",
    year: 2024,
    description: "Neural Info. Processing Systems",
    submission_deadline: "2024-05-20",
    review_deadline: "2024-11-15",
    camera_ready_deadline: "2024-12-01",
    notification_date: "2024-09-15",
    conference_date: "2024-12-10",
    location: "Vancouver, Canada",
    status: "active",
    tracks: [],
    reviewed_papers: 0,
    total_papers: 6,
    domain: "Machine Learning",
  },
  {
    id: "3",
    name: "Assoc. for Adv. of AI",
    acronym: "AAAI 2024",
    year: 2024,
    description: "Assoc. for Adv. of AI",
    submission_deadline: "2023-09-01",
    review_deadline: "2024-02-15",
    camera_ready_deadline: "2024-03-01",
    notification_date: "2023-11-15",
    conference_date: "2024-02-20",
    location: "Washington DC, USA",
    status: "completed",
    tracks: [],
    reviewed_papers: 4,
    total_papers: 4,
    domain: "Artificial Intelligence",
  },
  {
    id: "4",
    name: "Intl. Conf. on Machine Learning",
    acronym: "ICML 2024",
    year: 2024,
    description: "Intl. Conf. on Machine Learning",
    submission_deadline: "2024-02-01",
    review_deadline: "2024-06-15",
    camera_ready_deadline: "2024-07-01",
    notification_date: "2024-04-15",
    conference_date: "2024-07-20",
    location: "Vienna, Austria",
    status: "completed",
    tracks: [],
    reviewed_papers: 3,
    total_papers: 3,
    domain: "Machine Learning",
  },
  {
    id: "5",
    name: "Assoc. for Comp. Linguistics",
    acronym: "ACL 2023",
    year: 2023,
    description: "Assoc. for Comp. Linguistics",
    submission_deadline: "2023-01-01",
    review_deadline: "2023-05-15",
    camera_ready_deadline: "2023-06-01",
    notification_date: "2023-04-15",
    conference_date: "2023-07-10",
    location: "Toronto, Canada",
    status: "closed",
    tracks: [],
    reviewed_papers: 2,
    total_papers: 2,
    domain: "Natural Language Processing",
  },
]

export const MOCK_EXPLORE_CONFERENCES: ReviewerConference[] = [
  {
    id: "exp_1",
    name: "International Conference on Computer Vision",
    acronym: "ICCV 2025",
    year: 2025,
    description: "International Conference on Computer Vision",
    submission_deadline: "2025-03-01",
    review_deadline: "2025-10-15",
    camera_ready_deadline: "2025-11-01",
    notification_date: "2025-08-15",
    conference_date: "2025-10-25",
    location: "Paris, France",
    status: "upcoming",
    tracks: [],
    reviewed_papers: 0,
    total_papers: 2400,
    domain: "Computer Vision",
  },
  {
    id: "exp_2",
    name: "Special Interest Group on Computer Graphics",
    acronym: "SIGGRAPH 2025",
    year: 2025,
    description: "Special Interest Group on Computer Graphics",
    submission_deadline: "2025-01-15",
    review_deadline: "2025-08-01",
    camera_ready_deadline: "2025-08-15",
    notification_date: "2025-05-15",
    conference_date: "2025-08-10",
    location: "Vancouver, Canada",
    status: "active",
    tracks: [],
    reviewed_papers: 0,
    total_papers: 1800,
    domain: "Graphics",
  },
  {
    id: "exp_3",
    name: "Knowledge Discovery and Data Mining",
    acronym: "KDD 2025",
    year: 2025,
    description: "Knowledge Discovery and Data Mining",
    submission_deadline: "2025-02-15",
    review_deadline: "2025-09-10",
    camera_ready_deadline: "2025-10-01",
    notification_date: "2025-06-15",
    conference_date: "2025-09-20",
    location: "Long Beach, USA",
    status: "open",
    tracks: [],
    reviewed_papers: 0,
    total_papers: 3100,
    domain: "Data Science",
  },
  {
    id: "exp_4",
    name: "Association for Computational Linguistics",
    acronym: "ACL 2025",
    year: 2025,
    description: "Association for Computational Linguistics",
    submission_deadline: "2025-01-20",
    review_deadline: "2025-07-05",
    camera_ready_deadline: "2025-08-01",
    notification_date: "2025-05-15",
    conference_date: "2025-07-15",
    location: "Dublin, Ireland",
    status: "upcoming",
    tracks: [],
    reviewed_papers: 0,
    total_papers: 4200,
    domain: "NLP",
  },
]

export const MOCK_ASSIGNMENTS: AssignmentWithPaper[] = [
  {
    assignment_id: 101,
    paper_id: 201,
    paper_title: "Efficient Vision Transformers for Edge Devices",
    conference_id: 1,
    conference_name: "CVPR 2024",
    status: "in_progress",
    due_date: "2024-05-15",
    days_left: 2,
  },
  {
    assignment_id: 102,
    paper_id: 202,
    paper_title: "Robust Object Detection in Adverse Weather Conditions",
    conference_id: 1,
    conference_name: "CVPR 2024",
    status: "not_started",
    due_date: "2024-05-15",
    days_left: 2,
  },
  {
    assignment_id: 103,
    paper_id: 301,
    paper_title: "Scaling Laws for Language Models",
    conference_id: 2,
    conference_name: "NeurIPS 2024",
    status: "not_started",
    due_date: "2024-11-15",
    days_left: 180,
  },
  {
    assignment_id: 104,
    paper_id: 401,
    paper_title: "Ethical Considerations in Generative AI",
    conference_id: 3,
    conference_name: "AAAI 2024",
    status: "completed",
    due_date: "2024-02-15",
    days_left: -10,
  },
]

export const MOCK_STATS: ReviewerStats = {
  total_assigned: 4,
  pending: 2,
  in_progress: 1,
  completed: 1,
  pending_requests: 0,
}
